# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f9b0c69c01d1eaab381e0e60b196c65c"
name = "checkoutdemos"
handle = "checkoutdemos"
application_url = "https://horrible-substitute-gap-disabilities.trycloudflare.com"
embedded = true

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_checkouts,read_companies,read_customers,read_discounts,read_orders,write_cart_transforms,write_checkouts,write_companies,write_customers,write_discounts,write_orders"

[auth]
redirect_urls = ["https://horrible-substitute-gap-disabilities.trycloudflare.com/auth/callback", "https://horrible-substitute-gap-disabilities.trycloudflare.com/auth/shopify/callback", "https://horrible-substitute-gap-disabilities.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true
